### ISSUE TITLE
ca.crt with py.pi instalation

### ISSUE THREAD

**Issue by srdjanStankovic** [Wolkabout/WolkConnect-Python#42]

**Comment by srdjastankovic** [comment]
Additionally,
on pi.py need to be added link for download ca.crt. Maybe to link to location into repo, this: https://github.com/Wolkabout/WolkConnect-Python/blob/master/wolk/ca.crt

and this line in snippet needs to updated from this:
 ca_cert=".." + os.sep + ".." + os.sep + "wolk" + os.sep + "ca.crt"
to this:
 ca_cert="ca.crt"
